service: janitor-lambda

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - "lambda:*"
      Resource: "*"

functions:
  clean:
    handler: functions/clean.handler
    events:
      - schedule: rate(1 hour)